services:
  # database:
  #   image: mariadb:latest
  #   environment:
  #     - MARIADB_ROOT_PASSWORD=example
  frontend:
    build: ./frontend
    ports:
      - 80:3000
    # depends_on:
      # - backend
  backend:
    build: ./backend/
    ports:
      - 8080:8080