services:
  database:
    image: postgres:alpine3.23
    environment:
      - POSTGRES_PASSWORD=/run/secrets/db_password.txt
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./init_scripts/init_database.sql:/docker-entrypoint-initdb.d/init_database.sql:ro
      - db-data:/var/lib/postgresql
    networks:
      - db_network
  frontend:
    build: ./frontend
    ports:
      - 80:3000
    networks:
      - backend_network
    depends_on:
      - backend
  backend:
    build: ./backend/
    ports:
      - 8080:8080
    networks:
      - db_network
      - backend_network
    depends_on:
      - database

volumes:
  db-data:

networks:
  db_network:
      driver: bridge
  backend_network:
      driver: bridge

secrets:
  db_password:
    file: db_password.txt